site_name: Rei Terauchi - MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Rei Terauchi
copyright: Copyleft 2021 "Rei Terauchi" - GNU Free Documentation License
repo_name: 'mdefweb : Github Repo'
site_url: https://terauchi-rei.github.io/mdefweb/
repo_url: 'https://github.com/terauchi-rei/mdefweb'

extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/medium
      link: https://medium.com/@reiterauchi
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/ponpon0505/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fujisanrei
    - icon: fontawesome/brands/github
      link: "https://github.com/terauchi-rei"

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: pink
    accent: white
  font:
    # See available fonts at https://fonts.google.com/
    text: Be Vietnam
    code: Cutive Mono
  icon:
    logo: material/memory
  favicon: images/favicon.svg
  features:
    - navigation.tabs

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
